[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "php82Extensions.pdo_pgsql", "php82Extensions.bcmath", "php82Extensions.mbstring", "php82Extensions.tokenizer", "php82Extensions.xml", "php82Extensions.curl"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[phases.start]
cmds = [
  "php artisan migrate --force",
  "php artisan serve --host=0.0.0.0 --port=$PORT"
]
